import { GitHubRepositoryType, GitHubUserType } from "./types/api";

export const USER_MOCK: GitHubUserType = {
  login: "sampleUser",
  id: 123456,
  node_id: "sampleNodeId",
  avatar_url: "https://example.com/avatar.png",
  gravatar_id: "sampleGravatarId",
  url: "https://api.github.com/users/sampleUser",
  html_url: "https://github.com/sampleUser",
  followers_url: "https://api.github.com/users/sampleUser/followers",
  following_url: "https://api.github.com/users/sampleUser/following{/other_user}",
  gists_url: "https://api.github.com/users/sampleUser/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sampleUser/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sampleUser/subscriptions",
  organizations_url: "https://api.github.com/users/sampleUser/orgs",
  repos_url: "https://api.github.com/users/sampleUser/repos",
  events_url: "https://api.github.com/users/sampleUser/events{/privacy}",
  received_events_url: "https://api.github.com/users/sampleUser/received_events",
  type: "User",
  site_admin: false,
  name: "Sample User",
  company: "Example Company",
  blog: "https://example.com/blog",
  location: "Somewhere",
  email: "sampleuser@example.com",
  hireable: true,
  bio: "I'm a sample user on GitHub, I'm a sample user on GitHub, I'm a sample user on GitHub, I'm a sample user on GitHub, I'm a sample user on GitHub, I'm a sample user on GitHub",
  twitter_username: "sampleTwitter",
  public_repos: 10,
  public_gists: 5,
  followers: 20,
  following: 15,
  created_at: "2023-01-01T00:00:00Z",
  updated_at: "2023-01-02T00:00:00Z",
};

export const REPOS_MOCK: GitHubRepositoryType[] = [{
  id: 123456,
  node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY=",
  name: "sample-repo",
  full_name: "sampleUser/sample-repo",
  private: false,
  owner: {
    login: "sampleUser",
    id: 123456,
    node_id: "MDQ6VXNlcjEyMzQ1Ng==",
    avatar_url: "https://avatars.githubusercontent.com/u/123456?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sampleUser",
    html_url: "https://github.com/sampleUser",
    followers_url: "https://api.github.com/users/sampleUser/followers",
    following_url: "https://api.github.com/users/sampleUser/following{/other_user}",
    gists_url: "https://api.github.com/users/sampleUser/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sampleUser/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sampleUser/subscriptions",
    organizations_url: "https://api.github.com/users/sampleUser/orgs",
    repos_url: "https://api.github.com/users/sampleUser/repos",
    events_url: "https://api.github.com/users/sampleUser/events{/privacy}",
    received_events_url: "https://api.github.com/users/sampleUser/received_events",
    type: "User",
    site_admin: false,
  },
  html_url: "https://github.com/sampleUser/sample-repo",
  description: "This is a sample repository",
  fork: false,
  url: "https://api.github.com/repos/sampleUser/sample-repo",
  forks_url: "https://api.github.com/repos/sampleUser/sample-repo/forks",
  keys_url: "https://api.github.com/repos/sampleUser/sample-repo/keys{/key_id}",
  collaborators_url: "https://api.github.com/repos/sampleUser/sample-repo/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/sampleUser/sample-repo/teams",
  hooks_url: "https://api.github.com/repos/sampleUser/sample-repo/hooks",
  issue_events_url: "https://api.github.com/repos/sampleUser/sample-repo/issues/events{/number}",
  events_url: "https://api.github.com/repos/sampleUser/sample-repo/events",
  assignees_url: "https://api.github.com/repos/sampleUser/sample-repo/assignees{/user}",
  branches_url: "https://api.github.com/repos/sampleUser/sample-repo/branches{/branch}",
  tags_url: "https://api.github.com/repos/sampleUser/sample-repo/tags",
  blobs_url: "https://api.github.com/repos/sampleUser/sample-repo/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/sampleUser/sample-repo/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/sampleUser/sample-repo/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/sampleUser/sample-repo/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/sampleUser/sample-repo/statuses/{sha}",
  languages_url: "https://api.github.com/repos/sampleUser/sample-repo/languages",
  stargazers_url: "https://api.github.com/repos/sampleUser/sample-repo/stargazers",
  contributors_url: "https://api.github.com/repos/sampleUser/sample-repo/contributors",
  subscribers_url: "https://api.github.com/repos/sampleUser/sample-repo/subscribers",
  subscription_url: "https://api.github.com/repos/sampleUser/sample-repo/subscription",
  commits_url: "https://api.github.com/repos/sampleUser/sample-repo/commits{/sha}",
  git_commits_url: "https://api.github.com/repos/sampleUser/sample-repo/git/commits{/sha}",
  comments_url: "https://api.github.com/repos/sampleUser/sample-repo/comments{/number}",
  issue_comment_url: "https://api.github.com/repos/sampleUser/sample-repo/issues/comments{/number}",
  contents_url: "https://api.github.com/repos/sampleUser/sample-repo/contents/{+path}",
  compare_url: "https://api.github.com/repos/sampleUser/sample-repo/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/sampleUser/sample-repo/merges",
  archive_url: "https://api.github.com/repos/sampleUser/sample-repo/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/sampleUser/sample-repo/downloads",
  issues_url: "https://api.github.com/repos/sampleUser/sample-repo/issues{/number}",
  pulls_url: "https://api.github.com/repos/sampleUser/sample-repo/pulls{/number}",
  milestones_url: "https://api.github.com/repos/sampleUser/sample-repo/milestones{/number}",
  notifications_url: "https://api.github.com/repos/sampleUser/sample-repo/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/sampleUser/sample-repo/labels{/name}",
  releases_url: "https://api.github.com/repos/sampleUser/sample-repo/releases{/id}",
  deployments_url: "https://api.github.com/repos/sampleUser/sample-repo/deployments",
  created_at: "2023-01-01T00:00:00Z",
  updated_at: "2023-01-02T00:00:00Z",
  pushed_at: "2023-01-03T00:00:00Z",
  git_url: "git://github.com/sampleUser/sample-repo.git",
  ssh_url: "git@github.com:sampleUser/sample-repo.git",
  clone_url: "https://github.com/sampleUser/sample-repo.git",
  svn_url: "https://github.com/sampleUser/sample-repo",
  homepage: "https://sample-repo.com",
  size: 100,
  stargazers_count: 50,
  watchers_count: 30,
  language: "JavaScript",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  has_discussions: true,
  forks_count: 10,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 5,
  license: {
    key: "mit",
    name: "MIT License",
    spdx_id: "MIT",
    url: "https://api.github.com/licenses/mit",
    node_id: "MDc6TGljZW5zZTEz",
  },
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: ["sample", "repository", "GitHub"],
  visibility: "public",
  forks: 10,
  open_issues: 5,
  watchers: 30,
  default_branch: "main",
}];
